2019-02-12 20:30:24,233 ERROR:log_namespace.SocioManager Traceback (most recent call last):
  File "/home/gino_junchaya/Desarrollo/ClubInformatica/RFID/model/SocioManager.py", line 21, in listarSocios
    cur.execute(query)
psycopg2.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


2019-02-12 20:30:26,262 ERROR:log_namespace.SocioManager Traceback (most recent call last):
  File "/home/gino_junchaya/Desarrollo/ClubInformatica/RFID/model/SocioManager.py", line 20, in listarSocios
    cur = self.conn.cursor()
psycopg2.InterfaceError: connection already closed

2019-02-12 20:30:52,532 ERROR:log_namespace.SocioManager Traceback (most recent call last):
  File "/home/gino_junchaya/Desarrollo/ClubInformatica/RFID/model/SocioManager.py", line 93, in obtenerCarrera
    return Carrera(row[0], row[1])
TypeError: 'NoneType' object is not subscriptable

2019-02-12 20:40:32,776 ERROR:log_namespace.SocioManager Traceback (most recent call last):
  File "/home/gino_junchaya/Desarrollo/ClubInformatica/RFID/model/SocioManager.py", line 93, in obtenerCarrera
    return Carrera(row[0], row[1])
TypeError: 'NoneType' object is not subscriptable

